import React from 'react';
import ProfilePage from './ProfilePage';

export const metadata = {
    title: 'profile',
    description: 'Generated by create next app',
  }

export default function pages() {
  return (
    <ProfilePage/>
  )
}
